apps/Capture/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class FileForm(FlaskForm):
    file = StringField("file", validators=[DataRequired()])
    name = StringField("name")

apps/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired


class FileForm(FlaskForm):
    file = StringField("file", validators=[DataRequired()])
    name = StringField("name")
    id = StringField("id")

apps/Capture/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'Capture_blueprint',
    __name__,
    url_prefix='/Capture'
)

apps/Capture/routes.py
import base64
import json
import os
import pickle
import uuid

import cv2
import numpy as np
from flask import render_template, request, jsonify, url_for, redirect, flash
from flask_login import login_required

from apps import upload_dir, models_dir, face_names_dir, fonts_dir
from apps.Capture import blueprint
from .forms import FileForm


# 분류기
detector = cv2.CascadeClassifier(os.path.join(models_dir, "haarcascades", "haarcascade_frontalface_default.xml"))


class NumpyEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, np.ndarray):
            return obj.tolist()
        return json.JSONEncoder.default(self, obj)


def on_json_loading_failed_return_dict(e):
    return {}


# 얼굴 감지(backend)
@blueprint.route("/detect", methods=["POST"])
@login_required
def detect_post():
    request.on_json_loading_failed = on_json_loading_failed_return_dict
    if request.get_json()["imageData"]:
        # base64 데이터를 OpenCV 이미지 데이터로 변환하기
        im_bytes = base64.b64decode(request.get_json()["imageData"])
        img_arr = np.frombuffer(im_bytes, dtype=np.uint8)
        img = cv2.imdecode(img_arr, flags=cv2.IMREAD_COLOR)

        # 흑백처리(BGR -> GRAY)
        img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # 얼굴 찾기
        try:
            faces = detector.detectMultiScale(img_gray)
            print(faces)

            # 찾은 얼굴
            for (x, y, w, h) in faces:
                cv2.rectangle(img, (x, y), (x + w, y + h), (0, 0, 255), 1)
        except:
            pass

        # 이미지 파일을 base64로 인코딩
        img_jpg = cv2.imencode(".jpg", img)
        image_base64 = base64.b64encode(img_jpg[1]).decode("utf-8")

        return jsonify(image_base64=image_base64)
    return jsonify()


# 얼굴 감지(frontend)
@blueprint.route("/detect", methods=["GET"])
@login_required
def detect():
    return render_template("face/detect.html")


# 실시간 얼굴 감지(frontend)
@blueprint.route("/Capture", methods=["GET"])
@login_required
def detect_realtime():
    return render_template("face/Capture.html")

# 이름 삭제
@blueprint.route("/name_delete/<string:name>")
@login_required
def name_delete(name):
    name_path = os.path.join(upload_dir, "face_names", name)
    if os.path.exists(name_path):
        import shutil
        shutil.rmtree(name_path)
    flash("데이터가 삭제되었습니다.")
    return redirect(url_for("face_blueprint.name_list"))


# 얼굴 인식(이름에 해당하는 사진 목록)
@blueprint.route("/face_list/<string:name>", methods=["GET", "POST"])
@login_required
def face_list(name):
    form = FileForm(request.form)
    messages = []
    errors = []

    # 사진 등록
    if request.method == "POST":
        file = request.files["file"]
        if file and allowed_image_file(file.filename):
            # 확장자
            file_extension = file.filename.split(".")[-1]

            # 파일 저장
            new_filename = str(uuid.uuid4()) + "." + file_extension
            file.save(os.path.join(upload_dir, "face_names", name, new_filename))
            messages.append("데이터가 등록되었습니다.")

    # 사진 파일 불러오기
    faces = os.listdir(os.path.join(upload_dir, "face_names", name))

    face_list = []
    for face in faces:
        face_path = os.path.join(upload_dir, "face_names", name, face)

        # 이미지 파일을 base64로 인코딩
        with open(face_path, "rb") as img_file:
            image_base64 = base64.b64encode(img_file.read()).decode('utf-8')

        # 확장자
        file_extension = face.split(".")[-1]

        # 파일 생성 시간
        from datetime import datetime
        create_unixtime = os.path.getctime(face_path)
        create_timestamp = datetime.fromtimestamp(create_unixtime)
        create_datetime = datetime.strftime(create_timestamp, '%Y-%m-%d %H:%M:%S')

        # 파일 크기
        file_size = os.path.getsize(face_path)

        data = {"name": name, "image_base64": image_base64, "file_extension": file_extension, "file_name": face, "create_datetime": create_datetime, "file_size": file_size}
        face_list.append(data)

    return render_template("home/face_list.html", face_list=face_list, name=name, messages=messages, form=form)


# 사진 등록
@blueprint.route("/face_upload", methods=["POST"])
@login_required
def face_upload():
    form = FileForm(request.form)

    file = request.files["file"]
    name = form.data["name"]

    # 저장 위치
    name_path = os.path.join(upload_dir, "face_names", name)

    # 파일 저장
    new_filename = str(uuid.uuid4()) + ".png"
    file.save(os.path.join(name_path, new_filename))

    return jsonify(result="ok")


# 사진 삭제
@blueprint.route("/face_delete/<string:name>/<string:file_name>")
@login_required
def face_delete(name, file_name):
    file_path = os.path.join(upload_dir, "face_names", name, file_name)
    if os.path.exists(file_path):
        os.remove(file_path)
    flash("데이터가 삭제되었습니다.")
    return redirect(url_for("face_blueprint.face_list", name=name))


# 사진 학습
@blueprint.route("/train_face", methods=["POST"])
@login_required
def train_face():
    if not os.path.exists(custom_face_model_dir):
        os.makedirs(custom_face_model_dir)

    model_file = os.path.join(custom_face_model_dir, "encodings.pickle")
    if os.path.exists(model_file):
        os.remove(model_file)

    known_face_names = []
    known_face_encodings = []
    known_images_dirs = os.listdir(face_names_dir)

    for known_images_dir in known_images_dirs:
        known_file_path = os.path.join(face_names_dir, known_images_dir)
        known_files = os.listdir(known_file_path)

        for known_file in known_files:

            # 파일명, 확장자
            known_face_names.append(known_images_dir)

            # 인코딩
            known_image_path = os.path.join(known_file_path, known_file)
            known_image = face_recognition.load_image_file(known_image_path)
            known_face_encoding = face_recognition.face_encodings(known_image)[0]
            known_face_encodings.append(known_face_encoding)

    # 인코딩 데이터 저장
    data = {"encodings": known_face_encodings, "names": known_face_names}
    f = open(model_file, "wb")
    f.write(pickle.dumps(data))
    f.close()

    return jsonify(result="ok")


# 얼굴 인식(frontend)
@blueprint.route("/recognize", methods=["GET"])
@login_required
def recognize():
    return render_template("face/recognize.html")


# 실시간 얼굴 인식(frontend)
@blueprint.route("/recognize_realtime", methods=["GET"])
@login_required
def recognize_realtime():
    return render_template("face/recognize_realtime.html")


# 얼굴 인식(backend)
@blueprint.route("/recognize", methods=["POST"])
@login_required
def recognize_post():
    request.on_json_loading_failed = on_json_loading_failed_return_dict
    if request.get_json()["imageData"]:
        # 인코딩 모델 불러오기
        model_file = os.path.join(custom_face_model_dir, "encodings.pickle")
        data = pickle.loads(open(model_file, "rb").read())

        # base64 데이터를 OpenCV 이미지 데이터로 변환하기
        im_bytes = base64.b64decode(request.get_json()["imageData"])
        img_arr = np.frombuffer(im_bytes, dtype=np.uint8)
        img_bgr = cv2.imdecode(img_arr, flags=cv2.IMREAD_COLOR)
        img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
        img_gray = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)

        # 얼굴 찾기
        boxes = face_recognition.face_locations(img_rgb)
        encodings = face_recognition.face_encodings(img_rgb, boxes)

        # 얼굴 인식
        who_names = []
        for encoding in encodings:
            distances = face_recognition.face_distance(data["encodings"], encoding)

            name = "몰라"
            if min(distances) < 0.4:
                index = np.argmin(distances)
                name = data["names"][index]
            who_names.append(name)

        # 얼굴 표시
        for (top, right, bottom, left), name in zip(boxes, who_names):
            cv2.rectangle(img_bgr, (left, top), (right, bottom), (0, 0, 255), 1)
            cv2.rectangle(img_bgr, (left, bottom), (right, bottom + 25), (0, 0, 255), -1)

        # 이름 표시
        from PIL import ImageFont, ImageDraw, Image
        img_pillow = Image.fromarray(img_bgr)
        draw = ImageDraw.Draw(img_pillow)
        font = ImageFont.truetype(os.path.join(fonts_dir, "gulim.ttc"), 14)
        for (top, right, bottom, left), name in zip(boxes, who_names):
            draw.text((left + 10, bottom + 5), name, font=font, fill=(255, 255, 255))

        img_bgr = np.array(img_pillow)

        # 이미지 파일을 base64로 인코딩
        img_jpg = cv2.imencode(".jpg", img_bgr)
        image_base64 = base64.b64encode(img_jpg[1]).decode("utf-8")

        return jsonify(image_base64=image_base64)
    return jsonify()


"""
# 얼굴 인식(backend)
@blueprint.route("/recognize", methods=["POST"])
@login_required
def recognize_post():
    request.on_json_loading_failed = on_json_loading_failed_return_dict
    if request.get_json()["imageData"]:
        currentname = "unknown"

        model_file = os.path.join(custom_face_model_dir, "encodings.pickle")
        data = pickle.loads(open(model_file, "rb").read())

        # base64 데이터를 OpenCV 이미지 데이터로 변환하기
        im_bytes = base64.b64decode(request.get_json()["imageData"])
        img_arr = np.frombuffer(im_bytes, dtype=np.uint8)
        img = cv2.imdecode(img_arr, flags=cv2.IMREAD_COLOR)
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # 얼굴 찾기
        boxes = face_recognition.face_locations(img_rgb)
        encodings = face_recognition.face_encodings(img_rgb, boxes)

        names = []
        for encoding in encodings:
            matches = face_recognition.compare_faces(data["encodings"], encoding)
            name = "Unknown"

            if True in matches:
                # find the indexes of all matched faces then initialize a

apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""
import os
from apps import upload_dir
from flask import render_template, request, flash, redirect, url_for
from flask_login import login_required
from jinja2 import TemplateNotFound
from apps.home import blueprint
from .forms import FileForm


@blueprint.route('/')
def route_default():
    return render_template('home/choice.html', segment='choice')


@blueprint.route('/Capture')
def capture():
    return render_template('home/Capture.html', segment='choice')


@blueprint.route('/index')
@login_required
def index():
    return render_template('home/AdminMain.html', segment='index')


# 얼굴 인식(이름 목록)
@blueprint.route("/name_list", methods=["GET", "POST"])
@login_required
def name_list():
    # 사용자 이름 디렉터리 확인 후 없으면 생성
    face_names = os.path.join(upload_dir, "face_names")
    if not os.path.exists(face_names):
        os.makedirs(face_names)

    form = FileForm(request.form)
    name = form.name.data
    id = form.id.data
    messages = []

    if request.method == "POST":
        if name:
            # 디렉터리 생성
            name_dir = os.path.join(upload_dir, "face_names", name, id)
            if not os.path.exists(name_dir):
                os.makedirs(name_dir)
            messages.append("데이터가 등록되었습니다.")

    # 사용자 이름 불러오기
    names = os.listdir(face_names)

    name_list = []
    for name in names:
        name_path = os.path.join(upload_dir, "face_names", name)
        files = os.listdir(name_path)
        count = len(files)
        data = {"name": name, "count": count}
        name_list.append(data)

    return render_template("home/name_list.html", name_list=name_list, messages=messages, form=form)


# 이름 삭제
@blueprint.route("/name_delete/<string:name>")
@login_required
def name_delete(name):
    name_path = os.path.join(upload_dir, "face_names", name)
    if os.path.exists(name_path):
        import shutil
        shutil.rmtree(name_path)
    flash("데이터가 삭제되었습니다.")
    return redirect(url_for("Capture_blueprint.name_list"))


@blueprint.route('/<template>')
@login_required
def route_template(template):
    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):
    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None

apps/templates/home/Capture.html
{% extends "layouts/base_student.html" %}

{% block title %} 실시간 보기 {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
    <style>
        #video {
            width: 500px;
            height: 375px;
            background-color: #666;
        }
    </style>
{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->
    <div class="pcoded-main-container">
        <div class="pcoded-content">
            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">실시간 보기</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="#!">얼굴 인식</a></li>
                                <li class="breadcrumb-item"><a href="#!">실시간 보기</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->

            <!-- [ Main Content ] start -->
            <div class="row">

                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>카메라</h5>
                        </div>
                        <div class="card-body">
                            <video autoplay="true" id="video"></video>
                            <canvas class="d-none" id="capture" width="500" height="375"></canvas>
                        </div>
                        <div class="card-footer">
                            <button class="btn btn-sm btn-success btn-start mr-3">시작</button>
                            <button class="btn btn-sm btn-danger btn-stop">중지</button>
                            <button class="btn btn-sm btn-primary btn-capture">캡쳐</button>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6">
                    <div class="card">
                        <div class="card-header">
                            <h5>얼굴 감지</h5>
                        </div>
                        <div class="card-body">
                            <img src="https://via.placeholder.com/400" class="img-fluid img-thumbnail" id="image_base64">
                        </div>
                    </div>
                </div>

            </div>
            <!-- [ Main Content ] end -->
        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
        function start() {
            if (navigator.mediaDevices.getUserMedia) {
                navigator.mediaDevices.getUserMedia({video: true})
                    .then(function (stream) {
                        running = true;
                        video.srcObject = stream;
                    })
                    .catch(function (err0r) {
                        running = false;
                        console.log('Something went wrong!');
                    });
            }
        }

        function stop() {
            running = false;
            let stream = video.srcObject;
            let tracks = stream.getTracks();

            for (let i = 0; i < tracks.length; i++) {
                let track = tracks[i];
                track.stop();
            }

            video.srcObject = null;
        }

        let running = false;
        let video = document.querySelector('#video');

        start();

        // 시작
        $('.btn-start').on('click', function () {
            start();
        })

        // 중지
        $('.btn-stop').on('click', function () {
            stop();
        })

        function detectFace() {
            let capture = $('#capture')[0];
            let ctx = capture.getContext('2d');
            ctx.drawImage(video, 0, 0, capture.width, capture.height);

            let imgDataUrl = capture.toDataURL('image/png');
            let imageData = imgDataUrl.replace('data:image/png;base64,', '');

            $.ajax({
                type: "POST",
                data: JSON.stringify({"imageData": imageData}),
                url: "{{ url_for("Capture_blueprint.detect_post") }}",
                contentType: 'application/json; charset=utf-8',
                success: function (response) {
                    //console.log(response);
                    if (response) {
                        let image_base64 = response["image_base64"]
                        $("#image_base64").attr("src", "data:image/jpg;base64," + image_base64)
                    } else {
                        alert("예측 정보를 불러올 수 없습니다");
                    }
                },
                error: function(request, status, error){
                    alert(error);
                }
            });
        }

        setInterval(function() {
            if (running) detectFace();
        }, 100);
    </script>
{% endblock javascripts %}

apps/templates/home/StudentMain.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <!-- [ Main Content ] start -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}



{% endblock javascripts %}

apps/templates/home/choice.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} 출결인증시스템 {% endblock %}
>
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <main>
        <section class="vh-lg-100 mt-5 mt-lg-0 bg-soft d-flex align-items-center">
            <div class="container">
                <h1 class="h4 text-center">
                    명지전문대학 정보통신공학과
                </h1>
                <div class="row justify-content-center form-bg-image" data-background-lg="/static/assets/img/illustrations/signin.svg">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="bg-white shadow border-0 rounded border-light p-4 p-lg-5 w-100 fmxw-400">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">
                                    </br>
                                    출결인증 시스템입니다.
                                    </br></br></br></br></br>
                                    <div class = "block">
                                        <a href="Capture" class="btn btn-info btn-block btn-lg" > 학생 </a>
                                        <a href="AdminLogin" class="btn btn-lg btn-tertiary btn-block"> 교수 </a>
                                        </br></br>
                                    </div>
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/name_list.html
{% extends "layouts/base.html" %}

{% block title %} 학생등록 {% endblock %}

<!-- Specific CSS goes HERE-->
{% block stylesheets %}
   <!-- <style>
        #video {
            width: 500px;
            height: 375px;
            background-color: #666;
        }
    </style>-->
{% endblock stylesheets %}

{% block content %}
            {% with flushes = get_flashed_messages() %}
                {% if flushes %}
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <div>
                            {% for message in flushes %}
                                {{ message }}
                            {% endfor %}
                        </div>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                {% endif %}
            {% endwith %}

            {% if messages %}
                <div class="alert alert-primary alert-dismissible fade show" role="alert">
                    <div>
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
            {% endif %}

            {% if errors %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <div>
                        {% for error in errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                </div>
            {% endif %}

            <!-- [ Main Content ] start -->
            <div class="row">
                <!-- [ sample-page ] start -->
                <div class="col-sm-12">

                    <!-- 등록 -->
                    <div class="card">
                        <div class="card-header">
                            <h5>등록</h5>
                        </div>
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {{ form.csrf_token }}
                                <div class="form-group">
                                    <input type="text" class="form-control mb-2" id="id" name="id" placeholder="학번">
                                    <input type="text" class="form-control mb-2" id="name" name="name" placeholder="이름">
                                </div>
                                <button type="submit" class="btn btn-primary">등록</button>
                            </form>
                        </div>
                    </div>
                    <!--// 등록 -->

                    <div class="alert alert-primary alert-dismissible fade show d-none" role="alert" id="train_info">
                        <div>
                            <span id="train_msg"></span>
                        </div>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                    </div>

                    <!-- 목록 -->
                    <div class="card">
                        <div class="card-header">
                            <h5>목록</h5>
                            <div class="card-header-right">
                                <button type="button" class="btn btn-primary btm-sm btn-train-face-ajax mr-3">학습(ajax)</button>
                                <button class="btn btn-primary btn-train-face-ajax-loading d-none mr-3" type="button" disabled>
                                    <span class="spinner-border spinner-border-sm" role="status"
                                          aria-hidden="true"></span> 처리중...
                                </button>
                                <button type="button" class="btn btn-success btm-sm btn-train-face-socketio">학습(socketio)</button>
                                <button class="btn btn-success btn-train-face-socketio-loading d-none" type="button" disabled>
                                    <span class="spinner-border spinner-border-sm" role="status"
                                          aria-hidden="true"></span> 처리중...
                                </button>
                            </div>
                        </div>
                        <div class="card-body table-border-style">
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th>학번</th>
                                        <th>이름</th>
                                        <th>사진</th>
                                        <th>관리</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% if name_list %}
                                        {% for name in name_list %}
                                            <tr>
                                                <td>{{ name.id }}</td>
                                                <td>{{ name.name }}</td>
                                                <td>{{ name.count }}개</td>
                                                <td>
                                                    <a href="{{ url_for('Capture_blueprint.face_list', name=name.name) }}"
                                                       class="btn btn-sm btn-primary btn-faces">사진 관리</a>
                                                    <button data-url="{{ url_for('home_blueprint.name_delete', name=name.name) }}"
                                                            class="btn btn-sm btn-danger btn-delete">삭제
                                                    </button>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    {% else %}
                                        <tr>
                                            <td colspan="2" class="text-center">데이터가 없습니다.</td>
                                        </tr>
                                    {% endif %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!--// 목록 -->

                </div>
                <!-- [ sample-page ] end -->
            </div>
            <!-- [ Main Content ] end -->
        </div>
    </div>
    <!-- [ Main Content ] end -->

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
    <script>
        let training_face = false;

        socket.on('train face', function (data) {
            $('#train_msg').text(data);
            $('#train_info').removeClass('d-none');

            if (data == '얼굴 학습 완료') {
                $('.btn-train-face-ajax').removeClass('d-none');
                $('.btn-train-face-ajax-loading').addClass('d-none');
                $('.btn-train-face-socketio').removeClass('d-none');
                $('.btn-train-face-socketio-loading').addClass('d-none');
                training_face = false;
            }
        });

        $('.btn-train-face-socketio').on('click', function () {
            $('.btn-train-face-ajax').addClass('d-none');
            $('.btn-train-face-ajax-loading').addClass('d-none');
            $('.btn-train-face-socketio').addClass('d-none');
            $('.btn-train-face-socketio-loading').removeClass('d-none');
            socket.emit('train face', '');
            training_face = true;
        })

        $('.btn-train-face-ajax').on('click', function () {
            $('.btn-train-face-ajax').addClass('d-none');
            $('.btn-train-face-ajax-loading').removeClass('d-none');
            $('.btn-train-face-socketio').addClass('d-none');
            $('.btn-train-face-socketio-loading').addClass('d-none');
            training_face = true;

            $.ajax({
                type: 'POST',
                url: '{{ url_for("Capture_blueprint.train_face") }}',
                success: function (response) {
                    $('.btn-train-face-ajax').removeClass('d-none');
                    $('.btn-train-face-ajax-loading').addClass('d-none');
                    $('.btn-train-face-socketio').addClass('d-none');
                    $('.btn-train-face-socketio-loading').addClass('d-none');
                    training_face = false;
                    alert('학습이 완료되었습니다.')
                },
                error: function (request, status, error) {
                    alert(error);
                }
            });
        })
    </script>
{% endblock javascripts %}